baseurl = "http://striple.mooo.com/"
languageCode = "en-us"
title = "Émeric's ranting/rumbling & striple"
disqusShortname = "striple"
MetaDataFormat = "toml"
theme = "hydex"
paginate = 10

[author]
    name = "Émeric Chevalier"

[taxonomies]
    category = "categories"
    tag = "tags"

[[menu.main]]
    name = "Categories"
    weight = -110
    identifier = "categories"
    url = "/categories/"


[[menu.main]]
    name = "Tags"
    pre = ""
    weight = -100
    identifier = "tags"
    url = "/tags/"

[params]
    truncate = true # default value
    
    defaultDescription = "My blog about computer science related day dreaming"

    defaultKeywords = "striple,cheme,blog,trust,wot" # TODO add all tags

    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-09 layout-reverse"

    highlight = "monokai_sublime"

    tagline = "Dev,Design,Archi"

    home = "Posts"

    gravatarHash = "6db2711293800830a1bf2d918cebfe61"

    github = "http://github.com/cheme"
#    bitbucket = ""
    stackOverflow = "http://github.com/cheme" # TODO find it
    linkedin = "http://fr.linkedin.com/in/emericchevalier"
#    googleplus = ""
#    facebook = ""
#    twitter = ""
#    youtube = ""

    # Other social-like sidebar links
    rss = true  # switch to true to enable RSS icon link TODO try it latter
#    flattr = ""  # populate with your flattr uid
